import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const TRANSLATIONS = {
  id: {
    // Navigation
    nav_home: 'Beranda',
    nav_about: 'Tentang Kami',
    nav_products: 'Produk',
    nav_services: 'Layanan',
    nav_resources: 'Sumber Daya',
    nav_contact: 'Hubungi Kami',
    nav_lang_id: 'Indonesia',
    nav_lang_en: 'English',
    nav_quick_chat: 'WhatsApp Quick Chat',
    mobile_nav_heading: 'MENU UTAMA',
    mobile_lang_heading: 'BAHASA',

    // Hero Slider
    hero_badge_1: 'Formulasi Kimia Industri Terpercaya',
    hero_title_1: 'Solusi Kimia & Pengolahan Air Berstandar Tinggi',
    hero_desc_1: 'CV. Citra Putra Mandiri menghadirkan produk kimia berkualitas tinggi untuk sistem Boiler, Cooling Tower, Chiller, dan Perawatan Mesin Manufaktur.',
    hero_cta_1: 'Lihat Produk Kami',

    hero_badge_2: 'Perawatan Sistem Air & Solusi Pemeliharaan',
    hero_title_2: 'Efisiensi Energi & Perlindungan Kerak Dan Korosi',
    hero_desc_2: 'Mengoptimalkan kinerja pendinginan & pemanasan industri Anda dengan inhibitor korosi dan agen pembersih kerak tercanggih.',
    hero_cta_2: 'Jelajahi Solusi',

    hero_badge_3: 'Mitra Utama Pabrik & Manufaktur',
    hero_title_3: 'Dukungan Teknis & Pengiriman Seluruh Indonesia',
    hero_desc_3: 'Tim ahli kimia kami siap memberikan konsultasi gratis di lokasi pabrik Anda dan pasokan bahan kimia berkelanjutan.',
    hero_cta_3: 'Hubungi Tim Kami',

    hero_title_4: 'Pendinginan Optimal dengan Inhibitor Korosi Terbaik',
    hero_desc_4: 'Lindungi sistem cooling tower Anda dari kerak, korosi, dan pertumbuhan mikroba dengan formulasi kimia presisi dari CV. Citra Putra Mandiri.',

    hero_title_5: 'Solusi Ramah Lingkungan untuk Industri Berkelanjutan',
    hero_desc_5: 'Produk kimia kami diformulasikan dengan standar keamanan tinggi, minim limbah berbahaya, dan mendukung operasi pabrik yang lebih hijau dan efisien.',

    hero_consultation: 'Konsultasi Gratis',
    hero_explore: 'EXPLORE MORE',

    // About Section (Home)
    about_tag: 'Tentang Kami',
    about_headline_part1: 'Mitra Terpercaya Solusi Kimia Industri &',
    about_headline_part2: 'Pengolahan Air',
    about_desc_main: 'CV. Citra Putra Mandiri adalah penyedia terkemuka bahan kimia khusus industri, pengolahan air boiler, cooling tower, dan perawatan mesin pabrik di Indonesia. Berkomitmen pada standar kualitas tertinggi, kami siap membantu menjaga efisiensi dan usia pakai aset industri Anda.',
    about_point_1: '28+ Formulasi Kimia Industri Teruji & Bersertifikat',
    about_point_2: 'Dokumen Resmi MSDS & Technical Data Sheet (TDS)',
    about_point_3: 'Konsultasi Penentuan Dosis & Pendampingan Lapangan',
    about_point_4: 'Layanan Custom OEM Formulasi Sesuai Spesifikasi Mesin',
    about_more_btn: 'Selengkapnya Tentang Kami',

    // Statistics Bar
    stat_products: 'Produk Kimia',
    stat_products_sub: 'Unggulan',
    stat_categories: 'Kategori Solusi',
    stat_categories_sub: 'Spesialis Industri',
    stat_clients: 'Klien Pabrik',
    stat_clients_sub: 'Di Seluruh Indonesia',
    stat_experience: 'Tahun Pengalaman',
    stat_experience_sub: 'Dukungan Technical',

    // Featured Products (Home)
    feat_tag: 'Produk Unggulan',
    feat_title: 'Rangkaian Formulasi Kimia Terbaik untuk Industri Anda',
    feat_see_all: 'Lihat Semua',
    feat_products_suffix: 'Produk',

    // Services Section (Home)
    serv_tag: 'Layanan Kami',
    serv_main_title: 'Solusi Kimia Industri Penunjang Operasional Pabrik',
    serv_main_desc: 'Dukungan menyeluruh mulai dari analisis kualitas air, pasokan bahan kimia khusus, hingga konsultasi dosis dan pendampingan perawatan berkala.',
    serv_btn_learn_more: 'Baca Selengkapnya',
    serv_btn_consult: 'Konsultasi Layanan Ini',

    // Products Page & Cards
    prod_catalog_badge: 'Katalog Lengkap',
    prod_catalog_heading: 'Formulasi Kimia Industri & Water Treatment',
    prod_catalog_desc: 'Temukan lebih dari 28 solusi bahan kimia khusus untuk pemeliharaan boiler, cooling tower, pencegahan karat, dan pembersihan mesin pabrik.',
    prod_search_placeholder: 'Cari kode (contoh: R 1011) atau nama produk...',
    prod_sidebar_title: 'Kategori Produk',
    prod_showing: 'Menampilkan',
    prod_products_count: 'produk',
    prod_reset_filter: 'Reset Filter',
    prod_not_found_title: 'Produk Tidak Ditemukan',
    prod_not_found_desc: 'Tidak ada produk yang cocok dengan pencarian. Coba kata kunci lain atau reset filter.',
    prod_show_all_btn: 'Tampilkan Semua Produk',
    prod_featured_section_title: 'Produk Unggulan Formulasi Clenol',
    prod_featured_badge: '5 Produk Unggulan',
    prod_other_section_title: 'Katalog Formulasi Industri Lainnya',
    prod_other_count_suffix: 'Produk',
    cat_all: 'Semua Produk',
    cat_water: 'Cooling & Boiler Treatment',
    cat_cleaning: 'Cleaning & Degreasing',
    cat_rust: 'Rust Treatment & Protection',
    cat_electrical: 'Electrical & Insulation',
    cat_specialty: 'Specialty Chemicals',
    prod_view_detail: 'Lihat Detail & Spesifikasi',
    prod_packaging: 'Kemasan',
    prod_applications: 'Aplikasi Utama',
    prod_dosage: 'Dosis & Petunjuk Pakai',
    prod_req_msds: 'Minta MSDS / TDS',
    prod_featured: 'Unggulan',
    prod_code: 'Kode Produk',
    prod_properties: 'Karakteristik Fisik / Kimia',
    prod_close: 'Tutup',
    prod_btn_consult_wa: 'Konsultasi & Order via WhatsApp',
    prod_btn_pdf: 'Unduh Dokumen TDS (PDF)',
    prod_dosage_info_note: 'Dosis tepat ditentukan dari analisis sampel air pabrik Anda.',
    prod_dosage_info_label: 'Info Dosis:',
    prod_specialty_main_title: 'Formulasi Specialty Chemicals',
    prod_specialty_sub_title: 'Katalog Specialty Chemicals Lainnya',
    prod_specialty_sub_desc: 'Rangkaian lengkap formulasi aditif bahan bakar, anti spatter las, spindel oil, pembersih cetakan moulding, dan pelumas pembubutan logam.',
    mega_explore_title: 'Jelajahi Produk',
    mega_explore_all: 'Jelajahi Semua Produk',
    mega_view_catalog: 'Buka Katalog & Filter Lengkap',
    mega_featured_title: 'Formulasi Unggulan',
    mega_solutions_title: 'Layanan & Sumber Daya',
    mega_msds_tds: 'Dokumen Resmi MSDS & TDS',
    mega_boiler_guide: 'Panduan Descaling Boiler',
    mega_oem: 'Formulasi Custom OEM Mesin',
    mega_water_test: 'Uji Analisis Sampel Air',
    mega_wa_support: 'Konsultasi Tim Teknis WhatsApp',

    // About Page (Elevated Corporate Storytelling)
    about_page_badge: 'Profil Perusahaan',
    about_page_title: 'Tentang CV. Citra Putra Mandiri',
    about_page_lead: 'Solusi kimia industri & water treatment terpercaya untuk efisiensi sistem pabrik Anda.',
    about_hero_indicator: '01 / 09 • PROFIL KORPORASI',
    about_hero_scroll: 'GULIR UNTUK MENJELAJAH',

    about_who_tag: 'TENTANG KAMI',
    about_who_headline: 'Partner Teknis untuk Menjaga Performa & Keberlanjutan Sistem Industri Anda',
    about_history_badge: 'Sejarah & Pengalaman',
    about_history_title: 'Lebih Dari 15 Tahun Mendedikasikan Kualitas & Solusi Berkelanjutan',
    about_history_p1: 'Sejak awal berdiri, CV. Citra Putra Mandiri hadir untuk menjawab satu masalah nyata di lapangan: kerak, korosi, dan biofouling yang menggerogoti efisiensi mesin pabrik — dan menggerus biaya produksi setiap tahun.',
    about_history_p2: 'Dari penyedia bahan kimia lokal, kami tumbuh menjadi mitra teknis tepercaya bagi lebih dari 100 pabrik skala nasional di berbagai sektor strategis, mulai dari industri manufaktur, makanan & minuman (F&B), tekstil, pulp & paper, hingga fasilitas fabrikasi logam dan pembangkit energi.',
    about_history_p3: 'Kami percaya tidak ada dua pabrik yang sama. Karakteristik air baku, derajat kesadahan, dan konfigurasi mesin di setiap fasilitas itu unik — sehingga solusi generik justru berisiko. Karena itu, pendekatan kami selalu dimulai dari uji laboratorium, dilanjutkan rekomendasi dosis presisi, dan pendampingan berkala langsung di lapangan — bukan sekadar mengirim produk lalu selesai.',
    about_stat_1_num: '15+',
    about_stat_1_label: 'Tahun Pengalaman',
    about_stat_2_num: '100+',
    about_stat_2_label: 'Pabrik Terlayani',
    about_stat_3_num: '28+',
    about_stat_3_label: 'Formulasi Produk',

    // Visual Company Story Break
    about_visual_badge: 'KOMITMEN TEKNIS',
    about_visual_title: 'Lebih Dari Sekadar Penyedia Bahan Kimia Industri',
    about_visual_desc: 'Kami memadukan formulasi kimia presisi tinggi dengan pendampingan teknis langsung di lantai pabrik untuk mencegah pembentukan kerak, korosi pipa, dan inefisiensi energi operasional.',

    // Journey
    about_journey_badge: 'Perjalanan Kami',
    about_journey_title: 'Tonggak Perkembangan & Dedikasi Industri',
    about_journey_1_stage: 'Awal Berdiri',
    about_journey_1_title: 'Menjawab Tantangan Kerak & Korosi Mesin Pabrik',
    about_journey_1_desc: 'Didirikan untuk mengatasi permasalahan riil pada boiler dan cooling tower industri melalui formulasi kimia spesifik.',
    about_journey_2_stage: 'Riset & Formulasi',
    about_journey_2_title: 'Pengembangan 28+ Formulasi Kimia Khusus',
    about_journey_2_desc: 'Memperluas lini produk mencakup chemical cleaning, degreaser, pelindung karat, isolasi elektrik, hingga specialty chemicals.',
    about_journey_3_stage: 'Layanan Teknis Terpadu',
    about_journey_3_title: 'Uji Laboratorium & Dosis Presisi di Lapangan',
    about_journey_3_desc: 'Mengintegrasikan analisis kualitas air baku (TDS, pH, Hardness) dan pendampingan berkala langsung oleh tim teknis di pabrik.',
    about_journey_4_stage: 'Mitra Nasional',
    about_journey_4_title: 'Dipercaya 100+ Fasilitas Industri Nasional',
    about_journey_4_desc: 'Menjadi mitra strategis jangka panjang bagi berbagai sektor manufaktur skala nasional dengan jaminan suplai berkelanjutan.',

    // The Big Statement Moment
    about_statement_badge: 'FILOSOFI LAYANAN KAMI',
    about_statement_quote: 'Kami tidak hanya memasok produk formulasi kimia. Kami memastikan sistem industri Anda beroperasi dengan performa puncak dan terlindungi.',
    about_statement_sub: 'Komitmen kami adalah keandalan jangka panjang mesin pabrik Anda, efisiensi energi operasional, dan perlindungan total terhadap investasi sistem utilitas.',

    // What We Do
    about_what_badge: 'Solusi & Kapabilitas',
    about_what_title: 'Solusi Komprehensif untuk Sistem Industri yang Lebih Efisien & Terlindungi',
    about_what_desc: 'Rangkaian produk kimia formulasi khusus dan layanan teknis yang dirancang untuk memperpanjang usia pakai mesin serta menghemat energi operasional pabrik.',
    about_what_cta: 'Jelajahi Katalog Produk Lengkap',

    // Industries We Serve
    about_ind_badge: 'Cakupan Sektor',
    about_ind_title: 'Dipercaya di Berbagai Sektor Industri Strategis',
    about_ind_desc: 'Formulasi kimia dan metodologi teknis kami telah terbukti di berbagai lingkungan pabrik dengan standar operasional yang ketat.',
    about_ind_1_name: 'Industri Manufaktur & Perakitan',
    about_ind_1_desc: 'Pembersihan mesin, perlindungan cetakan moulding, dan degreasing komponen logam presisi.',
    about_ind_2_name: 'Makanan & Minuman (F&B)',
    about_ind_2_desc: 'Pengolahan air boiler dan cooling tower dengan standar keamanan tinggi dan pemantauan berkala.',
    about_ind_3_name: 'Tekstil & Garmen',
    about_ind_3_desc: 'Perawatan ketel uap bertekanan tinggi dan pencegahan kerak pada saluran pipa transmisi uap.',
    about_ind_4_name: 'Pulp & Paper',
    about_ind_4_desc: 'Pengendalian kerak kalsium, lumpur biologis, dan perlindungan korosi pada sistem sirkulasi air besar.',
    about_ind_5_name: 'Fabrikasi Logam & Baja',
    about_ind_5_desc: 'Penghilang karat berat, pasivasi permukaan logam, dan pelapisan antikarat jangka panjang.',
    about_ind_6_name: 'Pembangkit Energi & Utilitas',
    about_ind_6_desc: 'Efisiensi pertukaran panas chiller, kondensor, dan pendingin generator listrik pabrik.',

    // Vision & Mission
    about_principles_badge: 'Visi & Misi',
    about_vision_mission_title: 'Fondasi Arah & Komitmen Perusahaan',
    about_vision_heading: 'Visi Perusahaan',
    about_vision_text: 'Menjadi penyedia solusi kimia industri dan water treatment pilihan utama di Indonesia — dikenal atas integritas, inovasi produk, dan layanan teknis tanpa kompromi, sekaligus mendorong efisiensi energi dan kelestarian mesin industri demi mendukung pertumbuhan ekonomi nasional.',
    about_mission_heading: 'Misi Kami',
    about_mission_item1: 'Menghasilkan formulasi kimia dengan daya pembersih dan perlindungan tinggi, teruji secara laboratorium.',
    about_mission_item2: 'Memberikan pendampingan teknis dan analisis air berkala secara akurat, agar dosis selalu tepat sesuai kondisi aktual di lapangan.',
    about_mission_item3: 'Menjamin pengiriman tepat waktu dan pasokan berkelanjutan, sehingga operasional pabrik Anda tidak pernah terhambat.',

    // Values & Trust
    about_why_badge: 'Nilai-Nilai Utama',
    about_why_title: 'Prinsip Kerja & Integritas Kami',
    about_why_1_title: 'Kualitas Teruji',
    about_why_1_desc: 'Seluruh produk diproduksi sesuai standar mutu dan melalui uji efektivitas ketat sebelum sampai ke tangan Anda.',
    about_why_2_title: 'Respon Cepat',
    about_why_2_desc: 'Tim teknis kami siap merespon pertanyaan dan kendala lapangan dengan sigap — karena downtime mesin adalah biaya yang tidak bisa ditunda.',
    about_why_3_title: 'Integritas Tinggi',
    about_why_3_desc: 'Transparansi penuh atas spesifikasi bahan aktif, dosis yang disarankan, serta keamanan MSDS. Tidak ada yang ditutup-tutupi.',
    about_why_4_title: 'Fokus Solusi',
    about_why_4_desc: 'Keberhasilan kami diukur dari keberhasilan operasional mesin dan efisiensi biaya pabrik Anda — bukan dari volume penjualan semata.',

    // Technical Methodology (Bagaimana Kami Bekerja)
    about_trust_badge: 'Metodologi Kerja Teknis',
    about_trust_title: 'Bagaimana Kami Bekerja Bersama Fasilitas Anda',
    about_trust_step1_num: '01',
    about_trust_step1_stage: 'ANALISIS AIR',
    about_trust_step1_title: 'Uji Parameter Air Baku & Sistem',
    about_trust_step1_desc: 'Menguji sampel air baku di fasilitas Anda (TDS, pH, Hardness, Silica) untuk memahami akar permasalahan mesin secara presisi.',
    about_trust_step2_num: '02',
    about_trust_step2_stage: 'FORMULASI & DOSIS',
    about_trust_step2_title: 'Rekomendasi Formulasi & Dosis Presisi',
    about_trust_step2_desc: 'Merumuskan jenis chemical inhibitor atau cleaner yang tepat beserta takaran dosis optimal demi efisiensi biaya bahan.',
    about_trust_step3_num: '03',
    about_trust_step3_stage: 'PASOKAN & KEPATUHAN',
    about_trust_step3_title: 'Pasokan Tepat Waktu & Kepatuhan MSDS',
    about_trust_step3_desc: 'Menjamin ketersediaan stok konsisten dengan kelengkapan dokumen teknis MSDS dan TDS resmi untuk kepatuhan K3 pabrik.',
    about_trust_step4_num: '04',
    about_trust_step4_stage: 'MONITORING RUTIN',
    about_trust_step4_title: 'Pendampingan Berkala di Lapangan',
    about_trust_step4_desc: 'Tim teknisi hadir langsung untuk monitoring rutin, blowdown check, dan evaluasi performa mesin jangka panjang.',

    // Final CTA
    about_cta_headline: 'Menjaga Performa Sistem. Melindungi Investasi Industri Anda.',
    about_cta_title: 'Siap mengoptimalkan sistem pemanasan dan pendinginan pabrik Anda?',
    about_cta_desc: 'Hubungi tim teknis kami untuk konsultasi awal dan uji laboratorium air baku.',
    about_cta_btn: 'Hubungi Kami',
    about_cta_wa: 'Diskusi WhatsApp',

    // Services Page
    serv_page_badge: 'Layanan Profesional',
    serv_page_title: 'Layanan Pendampingan Teknis & Water Treatment Industri',
    serv_page_desc: 'Kami tidak hanya menyediakan bahan kimia formulasi, namun juga mendampingi tim operasional Anda dari tahap analisa air, kalkulasi dosis, hingga eksekusi pembersihan sistem.',
    serv_points_title: 'Cakupan Layanan Termasuk:',

    // Resources Page
    res_page_badge: 'Pusat Dokumentasi Teknis',
    res_page_title: 'Sumber Daya, MSDS & Application Guides',
    res_page_desc: 'Akses lembar data keselamatan bahan (MSDS), technical data sheet (TDS), dan panduan teknis operasional untuk efisiensi sistem industri Anda.',
    res_tab_docs: 'Katalog Dokumen MSDS & TDS',
    res_tab_guides: 'Panduan Teknis Aplikasi',
    res_search_ph: 'Cari nama produk, kode dokumen, atau panduan...',
    res_doc_available: 'Tersedia',
    res_doc_download_btn: 'Unduh TDS (PDF)',
    res_doc_request_btn: 'Minta Dokumen MSDS Resmi',
    res_modal_title: 'Pengajuan Dokumen MSDS / TDS Resmi',
    res_modal_desc: 'Isi data pabrik Anda untuk pengiriman lembar keselamatan bertanda tangan basah resmi.',
    res_form_name: 'Nama Pemohon *',
    res_form_company: 'Nama Perusahaan / Pabrik *',
    res_form_email: 'Email *',
    res_form_phone: 'No. WhatsApp *',
    res_form_notes: 'Catatan Tambahan',
    res_form_submit: 'Kirim Permintaan Dokumen',
    res_success_msg: 'Permintaan berhasil diajukan! Tim kami akan mengirimkan file ke email Anda.',
    res_guide_section_badge: 'Instruksi Kerja & Keselamatan',
    res_guide_section_title: 'Panduan Aplikasi Perawatan Mesin & Water Treatment',
    res_guide_section_desc: 'Kumpulan panduan teknis yang disusun oleh insinyur kimia CV. Citra Putra Mandiri untuk efisiensi maksimal dan keamanan kerja di lapangan.',
    res_preview_title: 'Preview Lembar Keselamatan (MSDS)',
    res_preview_manufacturer: 'PRODUSEN',
    res_preview_category: 'KATEGORI',
    res_preview_hazard: 'IDENTIFIKASI & IDENTIFIKASI BAHAYA',
    res_preview_hazard_desc: 'Formulasi khusus untuk pemeliharaan fasilitas industri. Hindari kontak langsung dengan mata dan kulit tanpa alat pelindung diri (gloves & safety goggles). Simpan di area berventilasi baik.',
    res_preview_first_aid: 'PERTOLONGAN PERTAMA',
    res_preview_fa_eye: 'Kontak Mata: Pembilasan dengan air bersih mengalir selama 15 menit.',
    res_preview_fa_skin: 'Kontak Kulit: Cuci dengan sabun dan air bersih.',
    res_preview_fa_storage: 'Penyimpanan: Simpan pada suhu ruangan 20-30°C terlindung dari sinar matahari langsung.',
    res_preview_pkg: 'KEMASAN RESMI',
    res_preview_download: 'Unduh Dokumen MSDS (PDF)',
    res_preview_btn: 'Preview MSDS',
    res_guide_read_time: 'baca',
    res_guide_recommended: 'Produk yang Direkomendasikan:',
    res_guide_steps: 'Tahapan Prosedur Kerja:',

    // Contact Form & Page
    contact_page_badge: 'Hubungi Kami',
    contact_page_title: 'Konsultasi Kimia Industri & Permintaan Penawaran',
    contact_page_desc: 'Tim ahli teknis CV. Citra Putra Mandiri siap memberikan rekomendasi produk dan dosis yang tepat untuk kebutuhan fasilitas Anda.',
    contact_subtitle: 'Hubungi Kami',
    contact_title: 'Konsultasi Kimia Industri & Permintaan Penawaran',
    contact_form_title: 'Tim ahli teknis CV. Citra Putra Mandiri siap memberikan rekomendasi produk dan dosis yang tepat untuk kebutuhan fasilitas Anda.',
    contact_form_heading: 'Kirim Pesan / Inkuiri Produk',
    contact_name_label: 'Nama Lengkap *',
    contact_name_ph: 'Bapak / Ibu Ahmad',
    contact_company_label: 'Nama Perusahaan / Pabrik *',
    contact_company_ph: 'PT Industri Utama',
    contact_email_label: 'Email Kerja *',
    contact_phone_label: 'Nomor Telepon / WhatsApp *',
    contact_prod_label: 'Produk / Layanan yang Dibutuhkan',
    contact_prod_ph: 'Pilih Kategori Kebutuhan',
    contact_msg_label: 'Pesan / Detail Masalah Teknis *',
    contact_msg_ph: 'Jelaskan kebutuhan volume, kendala kerak/karat pada mesin, atau sampel air yang ingin dianalisis...',
    contact_submit_btn: 'Kirim Pesan Inkuiri',
    contact_success_banner: 'Pesan Anda telah berhasil terkirim! Tim teknis kami akan segera menghubungi Anda.',
    contact_info_hq: 'Kantor Pusat & Operasional',
    contact_address_label: 'Alamat Kantor',
    contact_address_val: 'Ruko Munjul Permai Blok C No. 63, Kec. Solear, Kabupaten Tangerang - Banten',
    contact_info_call: 'Telepon & WhatsApp',
    contact_info_email: 'Email Resmi',
    contact_info_hours: 'Jam Layanan',
    contact_days_hours: 'Senin - Sabtu: 08:00 - 17:00 WIB',
    contact_wa_direct: 'Chat WhatsApp Langsung',
    contact_wa_desc: 'Respon cepat dari tim teknisi untuk konsultasi mendesak.',
    contact_delivery_title: 'Jangkauan Pengiriman Seluruh Indonesia',
    contact_delivery_desc: 'Melayani pengiriman bahan kimia industri ke seluruh kawasan industri & manufaktur di Indonesia.',
    about_val_3_title: 'Jangkauan Pengiriman Seluruh Indonesia',
    about_val_3_desc: 'Melayani pengiriman bahan kimia industri ke seluruh kawasan industri & manufaktur di Indonesia.',

    // FAQ Section
    faq_badge: 'FAQ / Pertanyaan Umum',
    faq_title: 'Pertanyaan Seputar Pemesanan & Teknis',
    faq_q1: 'Apakah bisa mendapatkan sampel produk untuk uji coba skala laboratorium pabrik?',
    faq_a1: 'Ya, CV. Citra Putra Mandiri memberikan sampel gratis (trial batch) untuk pengujian laboratorium atau uji performa pada mesin pabrik Anda.',
    faq_q2: 'Berapa minimal pemesanan (MOQ) untuk bahan kimia industri?',
    faq_a2: 'Kami melayani pemesanan fleksibel mulai dari skala kemasan Spray Can 400ml, Pail 20L, hingga pasokan rutin Drum 200L dan pengiriman tangki grosir.',
    faq_q3: 'Apakah setiap pembelian disertai dokumen MSDS dan TDS resmi?',
    faq_a3: 'Tentu saja. Seluruh produk dikirimkan lengkap dengan sertifikasi Material Safety Data Sheet (MSDS) dan Technical Data Sheet (TDS) sesuai regulasi keselamatan industri.',
    faq_q4: 'Bagaimana prosedur penentuan dosis pengolahan air boiler / cooling tower?',
    faq_a4: 'Tim teknis kami dapat melakukan kunjungan lapangan untuk mengambil sampel air feed/circulating, menganalisis nilai pH, TDS, Hardness, Silica, kemudian menghitung dosis yang presisi.',

    // Footer
    footer_brand_desc: 'CV. Citra Putra Mandiri adalah perusahaan penyedia solusi bahan kimia industri dan water treatment yang melayani kebutuhan pengolahan air boiler, cooling tower, serta pemeliharaan fasilitas manufaktur bagi berbagai sektor industri di Indonesia.',
    footer_menu_title: 'Menu Utama',
    footer_categories_title: 'Kategori Solusi',
    footer_hq_title: 'Informasi Kontak',
    footer_copyright: '© 2026 CV. Citra Putra Mandiri. All rights reserved.',
    footer_terms: 'Syarat & Ketentuan',
    footer_privacy: 'Kebijakan Privasi',
    footer_msds_link: 'Dokumen MSDS',
  },
  en: {
    // Navigation
    nav_home: 'Home',
    nav_about: 'About Us',
    nav_products: 'Products',
    nav_services: 'Services',
    nav_resources: 'Resources',
    nav_contact: 'Contact Us',
    nav_lang_id: 'Indonesia',
    nav_lang_en: 'English',
    nav_quick_chat: 'WhatsApp Quick Chat',
    mobile_nav_heading: 'MAIN NAVIGATION',
    mobile_lang_heading: 'LANGUAGE',

    // Hero Slider
    hero_badge_1: 'Trusted Industrial Chemical Formulations',
    hero_title_1: 'High-Standard Chemical & Water Treatment Solutions',
    hero_desc_1: 'CV. Citra Putra Mandiri delivers premium specialty chemicals for Boiler, Cooling Tower, Chiller systems, and Plant Machinery Maintenance.',
    hero_cta_1: 'Explore Our Products',

    hero_badge_2: 'Water Treatment Systems & Maintenance Solutions',
    hero_title_2: 'Energy Efficiency & Scale and Corrosion Protection',
    hero_desc_2: 'Optimize your industrial cooling & heating efficiency with advanced corrosion inhibitors and high-performance descaling agents.',
    hero_cta_2: 'Explore Solutions',

    hero_badge_3: 'Premier Partner for Industrial Plants',
    hero_title_3: 'Technical Support & Nationwide Delivery Across Indonesia',
    hero_desc_3: 'Our chemical engineers provide complimentary on-site technical consultations and reliable, long-term chemical supplies.',
    hero_cta_3: 'Contact Our Team',

    hero_title_4: 'Optimal Cooling with Premium Corrosion Inhibitors',
    hero_desc_4: 'Protect your cooling tower systems from scale, corrosion, and microbial foulants with precision formulations from CV. Citra Putra Mandiri.',

    hero_title_5: 'Eco-Friendly Solutions for Sustainable Operations',
    hero_desc_5: 'Our formulations meet rigorous industrial safety standards with minimal environmental footprint, supporting greener factory performance.',

    hero_consultation: 'Free Consultation',
    hero_explore: 'EXPLORE MORE',

    // About Section (Home)
    about_tag: 'About Us',
    about_headline_part1: 'Trusted Partner for Industrial Chemicals &',
    about_headline_part2: 'Water Treatment',
    about_desc_main: 'CV. Citra Putra Mandiri is a leading provider of specialty industrial chemicals, boiler water treatment, cooling towers, and factory machinery maintenance in Indonesia. Committed to the highest quality standards, we help maintain the efficiency and service life of your industrial assets.',
    about_point_1: '28+ Certified & Tested Industrial Chemical Formulations',
    about_point_2: 'Official Certified MSDS & Technical Data Sheet (TDS)',
    about_point_3: 'Dosage Consultation & On-site Technical Support',
    about_point_4: 'Custom OEM Formulation Services to Machine Specifications',
    about_more_btn: 'Learn More About Us',

    // Statistics Bar
    stat_products: 'Chemical Products',
    stat_products_sub: 'Flagship Quality',
    stat_categories: 'Solution Categories',
    stat_categories_sub: 'Industry Specialists',
    stat_clients: 'Industrial Plants',
    stat_clients_sub: 'Across Indonesia',
    stat_experience: 'Years Experience',
    stat_experience_sub: 'Technical Support',

    // Featured Products (Home)
    feat_tag: 'Featured Products',
    feat_title: 'Premier Chemical Formulations for Your Industrial Facility',
    feat_see_all: 'View All',
    feat_products_suffix: 'Products',

    // Services Section (Home)
    serv_tag: 'Our Services',
    serv_main_title: 'Industrial Chemical Solutions Supporting Factory Operations',
    serv_main_desc: 'Comprehensive support ranging from water quality analysis, specialty chemical supply, to dosage consulting and regular maintenance support.',
    serv_btn_learn_more: 'Read More',
    serv_btn_consult: 'Consult on This Service',

    // Products Page & Cards
    prod_catalog_badge: 'Complete Catalog',
    prod_catalog_heading: 'Industrial Chemical Formulations & Water Treatment',
    prod_catalog_desc: 'Discover over 28 specialty chemical solutions for boiler maintenance, cooling towers, rust prevention, and plant machinery cleaning.',
    prod_search_placeholder: 'Search code (e.g. R 1011) or product name...',
    prod_sidebar_title: 'Product Categories',
    prod_showing: 'Showing',
    prod_products_count: 'products',
    prod_reset_filter: 'Reset Filter',
    prod_not_found_title: 'No Products Found',
    prod_not_found_desc: 'No products matched your search query. Try different keywords or reset filters.',
    prod_show_all_btn: 'Show All Products',
    prod_featured_section_title: 'Flagship Clenol Formulations',
    prod_featured_badge: '5 Featured Products',
    prod_other_section_title: 'Other Industrial Chemical Formulations',
    prod_other_count_suffix: 'Products',
    cat_all: 'All Products',
    cat_water: 'Cooling & Boiler Treatment',
    cat_cleaning: 'Cleaning & Degreasing',
    cat_rust: 'Rust Treatment & Protection',
    cat_electrical: 'Electrical & Insulation',
    cat_specialty: 'Specialty Chemicals',
    prod_view_detail: 'View Details & Specifications',
    prod_packaging: 'Packaging',
    prod_applications: 'Main Applications',
    prod_dosage: 'Dosage & Directions',
    prod_req_msds: 'Request MSDS / TDS',
    prod_featured: 'Featured',
    prod_code: 'Product Code',
    prod_properties: 'Physical & Chemical Properties',
    prod_close: 'Close',
    prod_btn_consult_wa: 'Inquire & Order via WhatsApp',
    prod_btn_pdf: 'Download TDS Document (PDF)',
    prod_dosage_info_note: 'Precise dosage is calculated based on laboratory analysis of your plant\'s water sample.',
    prod_dosage_info_label: 'Dosage Guide:',
    prod_specialty_main_title: 'Featured Specialty Chemical Formulation',
    prod_specialty_sub_title: 'Other Specialty Chemical Products',
    prod_specialty_sub_desc: 'Comprehensive range of fuel treatment, welding anti-spatter, spindle oil, mould cleaner, and precision metal cutting lubricants.',
    mega_explore_title: 'Explore Products',
    mega_explore_all: 'Explore All Products',
    mega_view_catalog: 'View Full Catalog & Filters',
    mega_featured_title: 'Featured Formulations',
    mega_solutions_title: 'Services & Resources',
    mega_msds_tds: 'Certified MSDS & TDS Documents',
    mega_boiler_guide: 'Boiler Descaling Protocol',
    mega_oem: 'Custom OEM Machinery Formulation',
    mega_water_test: 'Water Sample Laboratory Testing',
    mega_wa_support: 'Direct Technical WhatsApp Support',

    // About Page (Elevated Corporate Storytelling)
    about_page_badge: 'Company Profile',
    about_page_title: 'About CV. Citra Putra Mandiri',
    about_page_lead: 'Trusted industrial chemicals & water treatment solutions for your plant efficiency.',
    about_hero_indicator: '01 / 09 • CORPORATE PROFILE',
    about_hero_scroll: 'SCROLL TO EXPLORE',

    about_who_tag: 'WHO WE ARE',
    about_who_headline: 'Your Technical Partner Safeguarding Industrial Performance & Reliability',
    about_history_badge: 'Our History & Experience',
    about_history_title: 'Over 15 Years of Dedication to Quality & Sustainable Solutions',
    about_history_p1: 'Since our inception, CV. Citra Putra Mandiri was established to solve a critical industrial challenge: scale, corrosion, and biofouling that degrade plant efficiency and inflate annual maintenance costs.',
    about_history_p2: 'From a specialized regional provider, we have evolved into a trusted technical partner for over 100 industrial plants nationwide across key sectors including manufacturing, food & beverage (F&B), textiles, pulp & paper, metal fabrication, and power generation.',
    about_history_p3: 'We recognize that no two industrial plants are identical. Raw water parameters, hardness levels, and equipment configurations are distinct—making generic solutions ineffective and risky. Our methodology always begins with laboratory analysis, precise dosage engineering, and hands-on site support.',
    about_stat_1_num: '15+',
    about_stat_1_label: 'Years of Experience',
    about_stat_2_num: '100+',
    about_stat_2_label: 'Plants Served',
    about_stat_3_num: '28+',
    about_stat_3_label: 'Product Formulations',

    // Visual Company Story Break
    about_visual_badge: 'TECHNICAL COMMITMENT',
    about_visual_title: 'More Than Just an Industrial Chemical Supplier',
    about_visual_desc: 'We combine high-precision chemical formulations with direct on-site technical support to eliminate scaling, pipe corrosion, and operational energy losses.',

    // Journey
    about_journey_badge: 'Our Journey',
    about_journey_title: 'Milestones & Industrial Dedication',
    about_journey_1_stage: 'Foundation',
    about_journey_1_title: 'Solving Plant Scaling & Corrosion',
    about_journey_1_desc: 'Established to overcome real operational challenges in boilers and cooling towers via targeted chemical formulations.',
    about_journey_2_stage: 'Research & Formulation',
    about_journey_2_title: 'Expansion to 28+ Specialty Formulations',
    about_journey_2_desc: 'Expanded formulation portfolio spanning cleaning, degreasers, rust protection, electrical insulation, and specialty chemicals.',
    about_journey_3_stage: 'Integrated Technical Service',
    about_journey_3_title: 'Laboratory Water Testing & Precision Dosing',
    about_journey_3_desc: 'Integrated comprehensive raw water analysis (TDS, pH, Hardness) with regular on-site technician support.',
    about_journey_4_stage: 'Nationwide Partnership',
    about_journey_4_title: 'Trusted by 100+ Industrial Facilities Nationwide',
    about_journey_4_desc: 'Serving as a long-term strategic partner across major manufacturing sectors with guaranteed supply continuity.',

    // The Big Statement Moment
    about_statement_badge: 'OUR SERVICE PHILOSOPHY',
    about_statement_quote: 'We do not merely supply formulated chemical products. We ensure your industrial systems operate at peak performance and remain fully protected.',
    about_statement_sub: 'Our commitment is the long-term reliability of your plant equipment, operational energy conservation, and total protection of your utility investments.',

    // What We Do
    about_what_badge: 'Solutions & Capabilities',
    about_what_title: 'Comprehensive Solutions for Efficient & Protected Industrial Systems',
    about_what_desc: 'Engineered chemical formulations and technical services designed to maximize machine lifespan and optimize operational energy for plant facilities.',
    about_what_cta: 'Explore Full Product Catalog',

    // Industries We Serve
    about_ind_badge: 'Industries We Serve',
    about_ind_title: 'Trusted Across Strategic Industrial Sectors',
    about_ind_desc: 'Our chemical formulations and technical methodologies are proven across diverse, demanding plant environments with strict operational standards.',
    about_ind_1_name: 'Manufacturing & Assembly',
    about_ind_1_desc: 'Machinery cleaning, mould release protection, and precision metal degreasing.',
    about_ind_2_name: 'Food & Beverage (F&B)',
    about_ind_2_desc: 'High-standard boiler and cooling tower water treatment with regular monitoring.',
    about_ind_3_name: 'Textile & Garment',
    about_ind_3_desc: 'High-pressure steam boiler maintenance and pipe transmission descaling.',
    about_ind_4_name: 'Pulp & Paper',
    about_ind_4_desc: 'Calcium scale inhibition, biological sludge control, and heavy-duty corrosion protection.',
    about_ind_5_name: 'Metal & Steel Fabrication',
    about_ind_5_desc: 'Heavy rust removal, metal surface passivation, and long-term anti-corrosion barrier.',
    about_ind_6_name: 'Power Generation & Utilities',
    about_ind_6_desc: 'Heat exchange efficiency in industrial chillers, condensers, and generator cooling.',

    // Vision & Mission
    about_principles_badge: 'Vision & Mission',
    about_vision_mission_title: 'Strategic Direction & Core Commitments',
    about_vision_heading: 'Our Vision',
    about_vision_text: 'To be the premier industrial chemical and water treatment provider in Indonesia—renowned for unwavering integrity, advanced product formulations, and responsive technical service while championing energy efficiency and industrial equipment longevity.',
    about_mission_heading: 'Our Mission',
    about_mission_item1: 'Manufacture high-potency chemical formulations with proven cleaning and protective efficacy through rigorous laboratory testing.',
    about_mission_item2: 'Provide accurate routine water analyses and precision on-site technical support to optimize dosing under actual plant operating conditions.',
    about_mission_item3: 'Guarantee prompt delivery schedules and reliable supply continuity to ensure zero downtime for your plant operations.',

    // Values & Trust
    about_why_badge: 'Core Values',
    about_why_title: 'Our Working Principles & Integrity',
    about_why_1_title: 'Proven Quality',
    about_why_1_desc: 'Every formulation is manufactured to stringent quality standards and passes thorough efficacy testing prior to delivery.',
    about_why_2_title: 'Fast Response',
    about_why_2_desc: 'Our technical team responds swiftly to urgent operational inquiries—because unexpected plant downtime is costly.',
    about_why_3_title: 'High Integrity',
    about_why_3_desc: 'Total transparency regarding active ingredient concentrations, recommended dosages, and complete certified MSDS documentation.',
    about_why_4_title: 'Solution-Focused',
    about_why_4_desc: 'Our performance is measured by your equipment reliability, efficiency gains, and operating cost reductions—not merely sales volume.',

    // Technical Methodology (Bagaimana Kami Bekerja)
    about_trust_badge: 'Technical Methodology',
    about_trust_title: 'How We Work With Your Facility',
    about_trust_step1_num: '01',
    about_trust_step1_stage: 'WATER ANALYSIS',
    about_trust_step1_title: 'Raw Water & System Testing',
    about_trust_step1_desc: 'Testing raw water samples from your facility (TDS, pH, Hardness, Silica) to accurately identify root machinery challenges.',
    about_trust_step2_num: '02',
    about_trust_step2_stage: 'FORMULATION & DOSING',
    about_trust_step2_title: 'Precision Formulation & Dosage Engineering',
    about_trust_step2_desc: 'Formulating the exact chemical inhibitor or cleaner with optimal dosing to maximize cost efficiency.',
    about_trust_step3_num: '03',
    about_trust_step3_stage: 'SUPPLY & COMPLIANCE',
    about_trust_step3_title: 'Reliable Supply & MSDS Compliance',
    about_trust_step3_desc: 'Ensuring continuous batch supply backed by official MSDS and TDS safety documentation for plant HSE compliance.',
    about_trust_step4_num: '04',
    about_trust_step4_stage: 'ROUTINE MONITORING',
    about_trust_step4_title: 'Routine On-Site Monitoring & Support',
    about_trust_step4_desc: 'Our technician team provides routine on-site monitoring, blowdown inspection, and long-term asset evaluation.',

    // Final CTA
    about_cta_headline: 'Safeguarding System Performance. Protecting Your Industrial Investment.',
    about_cta_title: 'Ready to optimize your factory heating and cooling systems?',
    about_cta_desc: 'Contact our technical team for initial consultation and raw water laboratory testing.',
    about_cta_btn: 'Contact Us',
    about_cta_wa: 'WhatsApp Discussion',

    // Services Page
    serv_page_badge: 'Professional Services',
    serv_page_title: 'Technical Support & Industrial Water Treatment Services',
    serv_page_desc: 'Beyond supplying chemical formulations, we support your plant operations through water analysis, dosage calculation, and system cleaning execution.',
    serv_points_title: 'Scope of Service Includes:',

    // Resources Page
    res_page_badge: 'Technical Documentation Hub',
    res_page_title: 'Resources, MSDS & Application Guides',
    res_page_desc: 'Access Material Safety Data Sheets (MSDS), Technical Data Sheets (TDS), and operational technical guides for your industrial systems.',
    res_tab_docs: 'MSDS & TDS Catalog',
    res_tab_guides: 'Technical Application Guides',
    res_search_ph: 'Search product name, document code, or guide...',
    res_doc_available: 'Available',
    res_doc_download_btn: 'Download TDS (PDF)',
    res_doc_request_btn: 'Request Official MSDS',
    res_modal_title: 'Official MSDS / TDS Document Application',
    res_modal_desc: 'Fill in your facility details below to request officially stamped and validated Safety Data Sheets.',
    res_form_name: 'Applicant Name *',
    res_form_company: 'Company / Factory Name *',
    res_form_email: 'Email *',
    res_form_phone: 'WhatsApp Number *',
    res_form_notes: 'Additional Notes',
    res_form_submit: 'Submit Document Request',
    res_success_msg: 'Request submitted successfully! Our team will send the files to your email.',
    res_guide_section_badge: 'Work Instructions & Safety',
    res_guide_section_title: 'Machinery Maintenance & Water Treatment Application Guides',
    res_guide_section_desc: 'Comprehensive technical procedures compiled by chemical engineers of CV. Citra Putra Mandiri for maximum operational efficiency and plant safety.',
    res_preview_title: 'Material Safety Data Sheet Preview (MSDS)',
    res_preview_manufacturer: 'MANUFACTURER',
    res_preview_category: 'CATEGORY',
    res_preview_hazard: 'HAZARD IDENTIFICATION & PRECAUTIONS',
    res_preview_hazard_desc: 'Specialized formulation for industrial maintenance. Avoid direct contact with skin and eyes without personal protective equipment (gloves & safety goggles). Store in a well-ventilated area.',
    res_preview_first_aid: 'FIRST AID MEASURES',
    res_preview_fa_eye: 'Eye Contact: Flush immediately with clean running water for at least 15 minutes.',
    res_preview_fa_skin: 'Skin Contact: Wash thoroughly with soap and running water.',
    res_preview_fa_storage: 'Storage: Store at room temperature (20-30°C) shielded from direct sunlight.',
    res_preview_pkg: 'OFFICIAL PACKAGING',
    res_preview_download: 'Download MSDS Document (PDF)',
    res_preview_btn: 'Preview MSDS',
    res_guide_read_time: 'read',
    res_guide_recommended: 'Recommended Products:',
    res_guide_steps: 'Procedure Workflow Steps:',

    // Contact Form & Page
    contact_page_badge: 'Contact Us',
    contact_page_title: 'Industrial Chemical Consulting & Quotation Request',
    contact_page_desc: 'Our technical experts at CV. Citra Putra Mandiri are ready to provide product recommendations and precise dosages for your facility.',
    contact_subtitle: 'Contact Us',
    contact_title: 'Industrial Chemical Consulting & Quotation Request',
    contact_form_title: 'Our technical experts at CV. Citra Putra Mandiri are ready to provide product recommendations and precise dosages for your facility.',
    contact_form_heading: 'Send Message / Product Inquiry',
    contact_name_label: 'Full Name *',
    contact_name_ph: 'Mr. / Mrs. John Doe',
    contact_company_label: 'Company / Plant Name *',
    contact_company_ph: 'PT Leading Industry',
    contact_email_label: 'Business Email *',
    contact_phone_label: 'Phone / WhatsApp Number *',
    contact_prod_label: 'Required Product / Service',
    contact_prod_ph: 'Select Solution Category',
    contact_msg_label: 'Message / Technical Problem Details *',
    contact_msg_ph: 'Describe volume requirements, scale/corrosion issues on machinery, or water samples to analyze...',
    contact_submit_btn: 'Send Inquiry Message',
    contact_success_banner: 'Your message has been sent successfully! Our technical team will contact you shortly.',
    contact_info_hq: 'Headquarters & Operations',
    contact_address_label: 'Office Address',
    contact_address_val: 'Ruko Munjul Permai Blok C No. 63, Solear, Tangerang Regency - Banten, Indonesia',
    contact_info_call: 'Phone & WhatsApp',
    contact_info_email: 'Official Email',
    contact_info_hours: 'Service Hours',
    contact_days_hours: 'Monday - Saturday: 08:00 - 17:00 WIB',
    contact_wa_direct: 'Direct WhatsApp Chat',
    contact_wa_desc: 'Fast response from our technical team for urgent consultations.',
    contact_delivery_title: 'Nationwide Delivery Coverage',
    contact_delivery_desc: 'Serving scheduled chemical deliveries to industrial and manufacturing zones across Indonesia.',
    about_val_3_title: 'Nationwide Delivery Coverage',
    about_val_3_desc: 'Serving scheduled chemical deliveries to industrial and manufacturing zones across Indonesia.',

    // FAQ Section
    faq_badge: 'FAQ / Frequently Asked Questions',
    faq_title: 'Questions About Ordering & Technical Support',
    faq_q1: 'Can we receive product trial samples for plant laboratory testing?',
    faq_a1: 'Yes, CV. Citra Putra Mandiri provides complimentary trial batch samples for laboratory evaluation or performance testing on your machinery.',
    faq_q2: 'What is the Minimum Order Quantity (MOQ) for industrial chemicals?',
    faq_a2: 'We offer flexible order quantities ranging from 400ml Spray Cans and 20L Pails to regular 200L Drum supplies and bulk shipments.',
    faq_q3: 'Is every order accompanied by official MSDS and TDS documents?',
    faq_a3: 'Absolutely. All products are delivered with certified Material Safety Data Sheets (MSDS) and Technical Data Sheets (TDS) in compliance with safety standards.',
    faq_q4: 'What is the procedure for determining boiler / cooling tower chemical dosing?',
    faq_a4: 'Our technical specialists can conduct on-site audits to collect water samples, analyze pH, TDS, Hardness, and Silica, and calculate precise dosages.',

    // Footer
    footer_brand_desc: 'CV. Citra Putra Mandiri is an industrial chemical and water treatment solutions provider serving boiler water treatment, cooling tower systems, and manufacturing facility maintenance for various industrial sectors across Indonesia.',
    footer_menu_title: 'Main Menu',
    footer_categories_title: 'Solution Categories',
    footer_hq_title: 'Contact Info',
    footer_copyright: '© 2026 CV. Citra Putra Mandiri. All rights reserved.',
    footer_terms: 'Terms & Conditions',
    footer_privacy: 'Privacy Policy',
    footer_msds_link: 'MSDS Documents',
  },
};

export function LanguageProvider({ children }) {
  const [lang, setLangState] = useState(() => {
    return localStorage.getItem('app_lang') || 'id';
  });

  const setLang = (newLang) => {
    setLangState(newLang);
    localStorage.setItem('app_lang', newLang);
  };

  const t = (key) => {
    return TRANSLATIONS[lang]?.[key] || TRANSLATIONS['id']?.[key] || key;
  };

  const trans = (val) => {
    if (!val) return '';
    if (typeof val === 'string') return val;
    if (Array.isArray(val)) return val;
    if (typeof val === 'object') {
      const res = val[lang] || val['id'] || val['en'] || '';
      return res;
    }
    return '';
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, trans }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
